version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  install-tools-and-build:
    executor:
      name: win/default
    steps:
    - run:
        command: choco install openjdk11 -y
    - run:
        command: choco install python -y
    - run:
        command: choco install msys2 -y --params "/InstallDir=C:\tools\msys64"
    - run:
        command: choco install bazel -y
    - run:
        command: git clone --depth 1 https://github.com/SeleniumHQ/selenium.git --branch trunk
    - run:
        command: |-
          cd selenium
          bazel build //dotnet/test/common:chrome

workflows:
  build-latest-selenium:
    jobs:
      - install-tools-and-build