version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  install-tools-and-build:
    executor:
      name: win/default
    steps:
    - run:
        command: go get github.com/tcnksm/ghr
    - run:
        command: choco install openjdk11 python -y
    - run:
        command: choco install bazel --version 4.2.2 -y
    - run:
        command: |-
          git clone --depth 10 https://github.com/SeleniumHQ/selenium.git --branch trunk
          cd selenium
          git reset --hard 447ab1f
    - run:
        command: |-
          cd selenium
          ((Get-Content -path dotnet\src\support\BUILD.bazel -Raw) -replace 'Selenium.Support', 'OutisNemo.Selenium.Support') | Set-Content -Path dotnet\src\support\BUILD.bazel
          bazel build --jobs=2 //dotnet/src/support:package
    - run:
        command: |-
          mkdir artifacts
          Get-ChildItem -Path "selenium\bazel-bin\dotnet\src\support\*" -Include *.nupkg,*.snupkg | Copy-Item -Destination artifacts\
    - store_artifacts:
          path: artifacts\

workflows:
  build-latest-selenium:
    jobs:
      - install-tools-and-build