version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  install-tools-and-build:
    executor:
      name: win/default
    steps:
    - run:
        command: go get github.com/tcnksm/ghr
    - run:
        command: choco install openjdk11 -y
    - run:
        command: choco install python -y
    - run:
        command: choco install msys2 -y --params "/InstallDir=C:\tools\msys64"
    - run:
        command: "[System.Environment]::SetEnvironmentVariable('BAZEL_SH', 'C:\\tools\\msys64\\usr\\bin\\bash.exe', [System.EnvironmentVariableTarget]::User)"
    - run:
        command: choco install bazel --version 4.2.2 -y
    - run:
        command: git clone --depth 1 https://github.com/SeleniumHQ/selenium.git --branch trunk
    - run:
        command: |-
          cd selenium
          ((Get-Content -path dotnet\src\support\BUILD.bazel -Raw) -replace 'Selenium.Support', 'OutisNemo.Selenium.Support') | Set-Content -Path dotnet\src\support\BUILD.bazel
          bazel build --jobs=2 //dotnet/src/support:package
    - run:
        command: |-
          mkdir artifacts
          Get-ChildItem -Path "selenium\bazel-bin\dotnet\src\webdriver\*" -Include *.nupkg,*.snupkg | Copy-Item -Destination artifacts\
    - store_artifacts:
          path: artifacts\

workflows:
  build-latest-selenium:
    jobs:
      - install-tools-and-build