version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  install-tools:
    executor:
      name: win/default
    steps:
    - run:
        command: choco install git -y
    - run:
        command: choco install openjdk11 -y
    - run:
        command: choco install python -y
    - run:
        command: choco install msys2 -y --params "/InstallDir=C:\tools\msys64"
    - run:
        command: choco install bazel -y
  build-selenium:
    executor:
      name: win/default
    steps:
    - run:
        command: git clone --depth 1 "$env:CIRCLE_REPOSITORY_URL" --branch "$env:CIRCLE_BRANCH"
    - run:
        command: |-
          cd selenium
          bazel build //dotnet/test/common:chrome

workflows:
  build-latest-selenium:
    jobs:
      - install-tools
      - build-selenium:
          requires:
            - install-tools