version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  install-tools-and-build:
    executor:
      name: win/default
    steps:
    - run:
        command: go get github.com/tcnksm/ghr
    - run:
        command: choco install openjdk11 -y
    - run:
        command: choco install python -y
    - run:
        command: choco install msys2 -y --params "/InstallDir=C:\tools\msys64"
    - run:
        command: choco install bazel --version 4.2.2 -y
    - run:
        command: git clone --depth 1 https://github.com/SeleniumHQ/selenium.git --branch trunk
    - run:
        command: |-
          cd selenium
          bazel build //dotnet/src/webdriver:package
          $line = Select-String -Path .\dotnet\selenium-dotnet-version.bzl -Pattern "SE_VERSION"
          $env:VERSION = [regex]::matches($line,'(?<=\").+?(?=\")').value
          ~\go\bin\ghr.exe -t $env:GITHUB_TOKEN -u $env:CIRCLE_PROJECT_USERNAME -r $env:CIRCLE_PROJECT_REPONAME -c $env:CIRCLE_SHA1 -soft $env:VERSION bazel-bin/dotnet/src/webdriver/*.nupkg

workflows:
  build-latest-selenium:
    jobs:
      - install-tools-and-build